project_name: golang-template-example

builds:
  - id: default
    main: ./main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

release:
  github:
    owner: FrancoPersonal
    name: golang-template-example

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"