name: Bug Report
description: File a bug report
title: "[BUG] "
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please complete the form below.

  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: "Brief description of the bug"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What did you expect to happen?

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: What actually happened?

  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: OS, Go version, browser, etc.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low
        - Medium
        - High
