    name: Go Tests

    on:
      push:
        branches: [ main, develop ]
      pull_request:
        branches: [ main, develop ]

    jobs:
      test:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

          - name: Set up Go
            uses: actions/setup-go@v5
            with:
              go-version: '1.24.5'

          - name: Download Go modules
            run: go mod tidy

          - name: Run tests
            run: go test -v ./...

          - name: Check if coverage is at least 80%
            run: |
              total=$(go tool cover -func=coverage/cover.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
              echo "Total coverage: $total%"
              threshold=80.0
              result=$(echo "$total >= $threshold" | bc)
              if [ "$result" -ne 1 ]; then
                echo "Coverage below threshold ($threshold%)"
                exit 1
              fi            